### ISSUE TITLE
Test latest version with a classic project

### ISSUE THREAD

**Issue by jwermuth** [danskespil/gradle-plugin-release#1]
Version 0.0.5 should be functionally equivivalent with the previous copy/paste version. Anyone (@mbrouer) !!

**Comment by jwermuth** [comment]
Work on this has been started by Kim Christensen.

**Comment by jwermuth** [comment]
Tests foretaget på internt DS projekt: 

Hej Jesper,
Jeg prøvede først en ”patch”:
./gradlew --stacktrace -i clean release -Prelease.stage=milestone -Prelease.scope=patch -xintegrationtest
Den brokkede sig over at jeg havde en milestone: 0.0.31-milestone.1 allerede
....

Hej Kim. Tak.
Jeg har forsøgt at reproducere, Trin:
- har lavet branch "feature-test-classic-release" og puttet din build.gradle fil derind
- jeg fulgte din første
…
./gradlew --stacktrace -i clean release -Prelease.stage=milestone -Prelease.scope=patch -xintegrationtest
som fejlede.
Så lavede jeg en final (jeg måtte snyde lidt, da jeg ikke kunne få adgang til docker registry)
Herefter kunne jeg lave
…

./gradlew --stacktrace -i clean release -Prelease.stage=milestone -Prelease.scope=patch -xintegrationtest

Så - det virker, ihvertfald lidt
Jeg bliver nødt til at stoppe nu. Mit gæt er, at nogle af de mange tags og release der er forsøgt får ajoberstar til at dø. Prøv at checke min branch ud og lave nogle releases og se hvad der sker.

**Comment by ekkichdanskespil** [comment]
Nu lykkedes det både at lave en final og en milestone. Det krævede "bare" at jeg brugte det rigtige netværk med adgang til vores repository. Jeg fortsætter med at kigge på branch versionen
