### ISSUE TITLE
Test version with branch - plugin version 0.0.9

### ISSUE THREAD

**Issue by ekkichdanskespil** [danskespil/gradle-plugin-release#3]
Working on branch: 
"feature/XXX-97/xxxx-xxxx-xxxx-xxxx"

Running command:
./gradlew --stacktrace -i clean release -Prelease.stage=branch -Prelease.scope=patch

Output:
...
Evaluating project ':psp' using build file 'C:\git\payment-service-proxy\psp\build.gradle'.
Skipping rebuild strategy because clean is true, "release." properties are true and head version is null
Skipping development strategy because stage (branch) is not one of: [dev]
Skipping pre-release strategy because stage (branch) is not one of: [milestone, rc]
Skipping final strategy because stage (branch) is not one of: [final]
Skipping snapshot strategy because stage (branch) is not one of: [SNAPSHOT]
Using branch strategy because repo is clean and stage (branch) is one of: [branch]
Beginning version inference using branch strategy and input scope (PATCH) and stage (branch)
LifecyclePlugin No [release] task. Adding it
LifecyclePlugin No [polish] task. Adding it
LifecyclePlugin Added [release] dependsOn [build]
LifecyclePlugin Added [release] dependsOn [publish]
LifecyclePlugin At this point, there is no task [publish] so it makes no sense to add a depency to [artifactoryPublish] to it. Skipping
LifecyclePlugin At this point, there is no task [check] so it makes no sense to add a depency to [integrationTest] to it. Skipping
LifecyclePlugin At this point, there is no task [polish] so it makes no sense to add a depency to [sonarqube] to it. Skipping
Skipping rebuild strategy because clean is true, "release." properties are true and head version is null
Skipping development strategy because stage (branch) is not one of: [dev]
Skipping pre-release strategy because stage (branch) is not one of: [milestone, rc]
Skipping final strategy because stage (branch) is not one of: [final]
Skipping snapshot strategy because stage (branch) is not one of: [SNAPSHOT]
Using branch strategy because repo is clean and stage (branch) is one of: [branch]
Beginning version inference using branch strategy and input scope (PATCH) and stage (branch)
Project evaluation failed including an error in afterEvaluate {}.
Unexpected character 'ILLEGAL(/)' at position '14', expecting '[PLUS, EOI]'
        at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
        at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:262)
        at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
        at com.github.zafarkhaja.semver.Version$Builder.build(Version.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
....

**Comment by ekkichdanskespil** [comment]
Nebula have had the same issue:
https://github.com/nebula-plugins/nebula-release-plugin/issues/46
Will investigate further

**Comment by ekkichdanskespil** [comment]
Thinking a solution where our "PreRelease" i changed to somewhat like:
https://github.com/nebula-plugins/nebula-release-plugin/blob/fd5d1cb366c5b403399f9ab4bc4ed72e05c0d174/src/main/groovy/nebula/plugin/release/NetflixOssStrategies.groovy#L50

Thus changing:
    static final class PreRelease {
        static final PartialSemVerStrategy BRANCH = closure { state -> state.copyWith(inferredPreRelease: state.currentBranch.name) }
    }

To:
    static final class PreRelease {
        static final PartialSemVerStrategy BRANCH = closure { state -> 

	    String shortenedBranchPattern = /(?:(?:bugfix|feature|hotfix|release)(?:-|\/))?(.+)/

            String shortenedBranch = (state.currentBranch.name =~ shortenedBranchPattern)[0][1]
            shortenedBranch = shortenedBranch.replaceAll(/[_\/-]/, '.')
            def metadata = "${shortenedBranch}.${state.currentHead.abbreviatedId}"

            state.copyWith(inferredBuildMetadata: metadata)
	}
    }

**Comment by jwermuth** [comment]
Nice finding. I think you are almost right: The way our plugin is configured at the moment, is by using the inferredPrelease, and instead of haved abbrevIds, we have an incrementing number (the number is configured elsewhere). 
So, I think it should like something like:

```
String shortenedBranch = /* whatever rewrite if the branch name that is required */
closure { state -> state.copyWith(inferredPreRelease:  shortenedBranch) }

```
We have do discuss exactly how the release.stage=branch should work. During that discussion we can change the behaviour to ... whatever we like. I do not know if we want to add special behaviour to branches with special naming like Nebula does, so I would not implement it for until we know we need it.

**Comment by jwermuth** [comment]
Fixed in pull   request
