### ISSUE TITLE
Allow multiple users to publish to gradle portal

### ISSUE THREAD

**Issue by jwermuth** [danskespil/gradle-plugin-release#5]
Currently we deploy to gradle portal using Jesper Wermuths ID. This means Jesper Wermuth is the only one who can publish the plugin to the gradle portal.
We want more people, e.g. all contributers to be able to deploy the plugin to the gradle portal. 

Figure out how to to this.

**Comment by jwermuth** [comment]
@ekkichdanskespil I think I fixed this at commit 991a68ef64c332f9653705507fb760c09a3fc7e1  and back to commit 510f73391a52cb60394b5977b94784fae7336023
Will you validate that it works for you by making a release to gradle portal and close/comment here

**Comment by ekkichdanskespil** [comment]
Something not working. Changed the release process slightly:

git checkout master
gw clean build release -Prelease.stage=final -Prelease.scope=patch
git checkout release
git merge master
git push --tags

Think it is working now
