### ISSUE TITLE
Test version with branch - plugin version 0.1.0

### ISSUE THREAD

**Issue by ekkichdanskespil** [danskespil/gradle-plugin-release#6]
First time with branch command worked:
./gradlew --stacktrace -i clean release -Prelease.stage=branch -Prelease.scope=patch

Branch name: "feature/XXX-97/using-new-release-plugin" got a new tag "0.0.61-feature-XXX-97-using-new-release-plugin". Very good :-)

Second call to branch command then failed:
./gradlew --stacktrace -i clean release -Prelease.stage=branch -Prelease.scope=patch

> Configure project :xxx
Evaluating project ':xxx' using build file 'C:\git\xxx-xxx-xxx\xxx\build.gradle'.
Skipping rebuild strategy because clean is true, "release." properties are true and head version is 0.0.61-milestone.1
Skipping development strategy because stage (branch) is not one of: [dev]
Skipping pre-release strategy because stage (branch) is not one of: [milestone, rc]
Skipping final strategy because stage (branch) is not one of: [final]
Skipping snapshot strategy because stage (branch) is not one of: [SNAPSHOT]
Using branch strategy because repo is clean and stage (branch) is one of: [branch]
Beginning version inference using branch strategy and input scope (PATCH) and stage (branch)
Inferred project: payment-service-proxy, version: 0.0.61-feature-XXX-97-using-new-release-plugin
LifecyclePlugin No [release] task. Adding it
LifecyclePlugin No [polish] task. Adding it
LifecyclePlugin Added [release] dependsOn [build]
LifecyclePlugin Added [release] dependsOn [publish]
LifecyclePlugin At this point, there is no task [publish] so it makes no sense to add a depency to [artifactoryPublish] to it. Skipping
LifecyclePlugin At this point, there is no task [check] so it makes no sense to add a depency to [integrationTest] to it. Skipping
LifecyclePlugin At this point, there is no task [polish] so it makes no sense to add a depency to [sonarqube] to it. Skipping
Skipping rebuild strategy because clean is true, "release." properties are true and head version is 0.0.61-milestone.1
Skipping development strategy because stage (branch) is not one of: [dev]
Skipping pre-release strategy because stage (branch) is not one of: [milestone, rc]
Skipping final strategy because stage (branch) is not one of: [final]
Skipping snapshot strategy because stage (branch) is not one of: [SNAPSHOT]
Using branch strategy because repo is clean and stage (branch) is one of: [branch]
Beginning version inference using branch strategy and input scope (PATCH) and stage (branch)
Inferred project: payment-service-proxy, version: 0.0.61-feature-XXX-97-using-new-release-plugin
Project evaluation failed including an error in afterEvaluate {}.
org.gradle.api.GradleException: Inferred version (0.0.61-feature-XXX-97-using-new-release-plugin) cannot be lower than nearest (0.0.61-milestone.1). Required by selected strategy.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
...

**Comment by ekkichdanskespil** [comment]
Another call to branch and final didn't work either:

./gradlew --stacktrace -i clean release -Prelease.stage=branch -Prelease.scope=final

> Configure project :xxx
Evaluating project ':xxx' using build file 'C:\git\xxx-xxx-xxx\xxx\build.gradle'.
Skipping rebuild strategy because clean is true, "release." properties are true and head version is 0.0.61-milestone.1
Skipping development strategy because stage (branch) is not one of: [dev]
Skipping pre-release strategy because stage (branch) is not one of: [milestone, rc]
Skipping final strategy because stage (branch) is not one of: [final]
Skipping snapshot strategy because stage (branch) is not one of: [SNAPSHOT]
Using branch strategy because repo is clean and stage (branch) is one of: [branch]
LifecyclePlugin No [release] task. Adding it
LifecyclePlugin No [polish] task. Adding it
LifecyclePlugin Added [release] dependsOn [build]
LifecyclePlugin Added [release] dependsOn [publish]
LifecyclePlugin At this point, there is no task [publish] so it makes no sense to add a depency to [artifactoryPublish] to it. Skipping
LifecyclePlugin At this point, there is no task [check] so it makes no sense to add a depency to [integrationTest] to it. Skipping
LifecyclePlugin At this point, there is no task [polish] so it makes no sense to add a depency to [sonarqube] to it. Skipping
Skipping rebuild strategy because clean is true, "release." properties are true and head version is 0.0.61-milestone.1
Skipping development strategy because stage (branch) is not one of: [dev]
Skipping pre-release strategy because stage (branch) is not one of: [milestone, rc]
Skipping final strategy because stage (branch) is not one of: [final]
Skipping snapshot strategy because stage (branch) is not one of: [SNAPSHOT]
Using branch strategy because repo is clean and stage (branch) is one of: [branch]
Project evaluation failed including an error in afterEvaluate {}.
java.lang.IllegalArgumentException: No enum constant org.ajoberstar.gradle.git.release.semver.ChangeScope.FINAL
        at java.lang.Enum.valueOf(Enum.java:238)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...

**Comment by jwermuth** [comment]
Ikke godt. Det kan testes ved at release pluginet selv. Det er noget
hurtigere end at skulle en tur forbi gradle portal. Den lille kodestump i
toppen af gradle scriptet loader plugin'et selv, ind i projektet. Så når
man skriver gradle release -P.... i gradle release plugin, så anvender man
pluginen selv til at lave release. Der kan også lave ordentlig automatisk
test. I givet fald anbefaler jeg at kigge på gradle-git plugin (som vi
arver fra) der er lavet en del tests.

**Comment by ekkichdanskespil** [comment]
Solved now in branch "feature/issue-6/multiple-branch-patches".
